version: '1.0.{build}'

image: Visual Studio 2017

branches:

  only:

  - master

init:

  # Good practise, because Windows line endings are different from Unix/Linux ones

  - cmd: git config --global core.autocrlf true

install:

  # Install repo specific stuff here

before_build:

  # Display .NET Core version

  - cmd: dotnet --version

  - cmd: dotnet restore ./Sharp7.Rx/Sharp7.Rx.csproj --verbosity m

build_script:

  - cmd: dotnet publish ./Sharp7.Rx/Sharp7.Rx.csproj -c Release

after_build:

  - ps:   _nuspec/pack.ps1

artifacts:

 - path: '**\*.nupkg'

   name: Sharp7.Rx_nuget

   type: Auto

clone_depth: 1

test_script:

  # restore packages for our unit tests

  - cmd: dotnet restore ./Sharp7.Rx.Tests/Sharp7.Rx.Tests.csproj --verbosity m
  
  # run the unit tests (requires changing into the test directory)

  #- cmd: cd Sharp7.Rx.Tests
  
  #- cmd: dotnet nunit

on_finish :

  # any cleanup in here

deploy: off